import Head from "next/head";

import { getSession, useSession } from "next-auth/client";

export default function Dashboard() {
  const [session] = useSession();

  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Hello, {session?.user?.name}!</h1>
    </>
  );
}

// export async function getServerSideProps(context) {
//   const session = await getSession(context);

//   return {
//     props: {
//       session,
//     },
//   };
// }
