import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import styled from "styled-components";

import Login from "../components/Login";

import { useSession, getSession, signOut } from "next-auth/client";

export default function Home() {
  const [session] = useSession();

  return (
    <>
      {!session && <Login />}
      {session && (
        <>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <UserContainer>
            <img src={session.user?.image} alt="user image" />
            <h1>Hello, {session.user?.name}</h1>
            <button onClick={signOut}>Sign out</button>
          </UserContainer>
        </>
      )}
    </>
  );
}

export async function getServerSideProps(context) {
  const session = await getSession(context);

  return {
    props: {
      session,
    },
  };
}

const UserContainer = styled.div`
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;

  width: 80%;
  height: 100vh;
  margin: auto;
`;
